const words = new URLSearchParams(window.location.search);


const name1=(words.get('Name1'));
const Age = (words.get('Age1'));
const RegNo  = (words.get('Reg_No1'));
const Date1  = (words.get('Date1'));
const ReferredBy  = (words.get('Referred1'));
const RBC = (words.get('RBC1'));
const WBC  = (words.get('WBC1'));
const Epithelial  = (words.get('epithelial1'));
const Casts  = (words.get('Casts1'));
const Crystals  = (words.get('Crystals1'));
const Bacteria  = (words.get('Bacteria1'));
const Color  = (words.get('Color1'));
const Quantity  = (words.get('Quantity1'));
const Apperance  = (words.get('Apperance1'));
const SG  = (words.get('SG1'));
const Sugar  = (words.get('Sugar1'));
const Blood  = (words.get('Blood1'));
const Proteins  = (words.get('Proteins1'));
const Reaction  = (words.get('Reaction1'));


console.log (name1);
const nameChange=document.getElementById('Name');
const AgeChange = document.getElementById("AgeSex");
const RegNoChange = document.getElementById("Reg_No");
const ReferredByChange = document.getElementById("Refereed_By");
const DateChange = document.getElementById("Date");
const RBCChange = document.getElementById("RBC");
const WBCChange = document.getElementById('WBC');
const EpithelialChange = document.getElementById('Epithelial_Cells');
const CastsChange = document.getElementById('Casts');
const CrystalsChange = document.getElementById('Crystals');
const BacteriaChange = document.getElementById('Bacteria');
const ColorChange = document.getElementById('Color');
const QuantityChange = document.getElementById('Quantity');
const ApperanceChange = document.getElementById('Appearnace');
const SGChange = document.getElementById('Specific_Gravity');
const SugarChange = document.getElementById('Sugar');
const BloodChange = document.getElementById('Blood');
const ProteinsChange = document.getElementById('Proteins');
const ReactionChange = document.getElementById('Reaction');

nameChange.innerHTML= name1;
AgeChange.innerHTML= Age;
RegNoChange.innerHTML= RegNo;
ReferredByChange.innerHTML= ReferredBy;
DateChange.innerHTML= Date1;
RBCChange.innerHTML= RBC;
WBCChange.innerHTML= WBC;
EpithelialChange.innerHTML= Epithelial;
CastsChange.innerHTML= Casts;
CrystalsChange.innerHTML= Crystals;
BacteriaChange.innerHTML= Bacteria;
ColorChange.innerHTML= Color;
QuantityChange.innerHTML= Quantity;
ApperanceChange.innerHTML= Apperance;
SGChange.innerHTML= SG;
SugarChange.innerHTML= Sugar;
BloodChange.innerHTML= Blood;
ProteinsChange.innerHTML= Proteins;
ReactionChange.innerHTML= Reaction;
